/**
 * All available Material Icons for category selection.
 */
export const ALL_ICONS: string[] = [
  // Finance & Shopping
  "payments",
  "shopping-cart",
  "shopping-bag",
  "savings",
  "account-balance",
  "credit-card",
  "attach-money",
  "receipt",
  "account-balance-wallet",
  "redeem",
  "card-giftcard",
  "monetization-on",
  "trending-up",
  "trending-down",
  "storefront",

  // Home & Life
  "home",
  "kitchen",
  "local-laundry-service",
  "flatware",
  "local-hotel",
  "bathtub",
  "weekend",
  "apartment",
  "family-restroom",
  "child-care",
  "pets",
  "grass",
  "cleaning-services",
  "electric-bolt",
  "water-drop",

  // Food & Drink
  "restaurant",
  "fastfood",
  "local-pizza",
  "bakery-dining",
  "coffee",
  "local-bar",
  "icecream",
  "cake",
  "local-grocery-store",
  "liquor",
  "lunch-dining",
  "ramen-dining",

  // Transport & Travel
  "directions-car",
  "directions-bus",
  "directions-bike",
  "directions-railway",
  "flight",
  "commute",
  "local-taxi",
  "electric-car",
  "moped",
  "pedal-bike",
  "tram",
  "sailing",
  "map",
  "hotel",
  "explore",

  // Entertainment & Hobby
  "movie",
  "sports-esports",
  "music-note",
  "palette",
  "camera-alt",
  "videogame-asset",
  "auto-stories",
  "theater-comedy",
  "piano",
  "fitness-center",
  "sports-soccer",
  "sports-basketball",
  "pool",
  "brush",
  "castle",

  // Work & Tech
  "work",
  "laptop-mac",
  "smartphone",
  "headset",
  "print",
  "mouse",
  "keyboard",
  "router",
  "watch",
  "construction",
  "build",
  "handyman",
  "biotech",
  "science",
  "terminal",

  // Health & Self-care
  "medical-services",
  "health-and-safety",
  "spa",
  "self-improvement",
  "vaccines",
  "medication",
  "masks",
  "healing",
  "monitor-heart",
  "psychology",

  // Misc
  "label",
  "bookmark",
  "star",
  "favorite",
  "notifications",
  "settings",
  "person",
  "group",
  "support-agent",
  "eco",
  "lightbulb",
  "lock",
  "shield",
];
